services:
  - type: web
    name: InterviewOS
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: NEXT_PUBLIC_APP_NAME
        value: HYRTE
